---
title: "Exploratory Data Analysis"
author: "Jordan Gropper"
date: '2022-07-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
# I want to turn off the running code for this, so the libraries are just shown
library(fixest)
library(ggplot2)
library(tidyverse)
library(vtable)
library(Ecdat)
library(ggstance)
library(multcomp)
library(NHANES)
```


```{r}

first_data <- read_csv('../RawData/firstdata.csv')
```
## The Questions:

1 How has COVID affected the health of the retail industry, as measured by employment?
2 How has retail fared relative to other industries?
3 Retail needs to worry about who has money to spend - what has changed about who is working and earning money?##

## Key Visuals:

Sean:
```{r}

colnames(first_data)

sean_data <- first_data %>% 
  select(REGION, WTFINL, NCHILD, CLASSWKR, COVIDUNAW, FAMINC, IncNumber, DIFFANY, YEAR, SERIAL, MONTH, HWTFINL, CPSID)

```
















































Andrew:
```{r}


"STATEFIP" "CPSIDP" "CITIZEN" "WHYUNEMP" "COVIDLOOK" "RACE"  "PERNUM"

```







































































Brooke:
```{r}

"METAREA" "AGE" "NATIVITY" "WKSTAT" "INDNAME" "EMPSTAT" "MARST"

```






































































Jordan:
```{r}
"CBSASZ" "SEX" "HISPAN" "EDUC" "monthyear" "SCHLCOLL" "IND"

```

































## Regression Approach:

### Model 1:
```{r}



```


### Model 2:
```{r}



```


### Model 3:
```{r}




```

















